{
    "SUCCESS_SAVING_PHYSICAL": "Saved changes to the Physical Address of ${0}", 
    "CONFIRM_EXIT_CCS": "There are unsaved changes to one or more copy statuses. Click OK to save these changes, or Cancel to abandon them.", 
    "SURVEY_SAVE_CHANGES": "\u00c4nderungen speichern", 
    "ERROR_CREATING_CHILD_AOU": "Problem creating child organizational unit", 
    "ERROR_CALLING_METHOD_PPL": "Problem calling method to create new permission", 
    "TRANSLATION": "Translation", 
    "ERROR_FETCHING_ORGS": "Problem fetching organizational unit data", 
    "SUCCESS_CREATING_STATUS": "New ${0} status created", 
    "SUCCESS_SAVING_HOLDS": "Saved changes to the Holds Address of ${0}", 
    "SUCCESS_SAVING_ILL": "Saved changes to the ILL Address of ${0}", 
    "STATUS_EDITING": "Bearbeite gerade ${0}", 
    "SUCCESS_SAVING_DATA": "\u00c4nderungen an ${0} gespeichert", 
    "SUCCESS_DELETED_PERM_MAP": "Permission mapping deleted", 
    "ERROR_SAVING_PERM_DATA": "Problem saving permission data for ${0}", 
    "ERROR_FETCHING_HOLDS": "Problem fetching Holds Address for ${0}", 
    "HOLDABLE": "Holdable", 
    "STATUS_DELETED": "${0} gel\u00f6scht", 
    "ERROR_CALLING_METHOD_CCS": "Problem calling method to create new copy status", 
    "SUCCESS_CREATING_CODE": "New ${0} ${1} created", 
    "ACQ_DISTRIB_FORMULA_NAME_PROMPT": "Enter new formula name", 
    "ERROR_SAVING_DATA": "Problem beim Speichern der Daten f\u00fcr ${0}", 
    "LABEL_NEW_BRANCH": "New Branch", 
    "ERROR_FETCHING_HOURS": "Problem fetching hours of operation for ${0}", 
    "LABEL_TRANSLATION": "Translation", 
    "ERROR_CREATING_PERMISSION": "Problem creating new Permission", 
    "LABEL_DESCRIPTION": "Beschreibung", 
    "ERROR_SAVING_HOO": "Problem saving Hours of Operation data for ${0}", 
    "SUCCESS_NEW_PERM_MAP": "New permission map created", 
    "END_SURVEY": "End Survey Now", 
    "CONFIRM_UNSAVED_CHANGES": "There are unsaved changes to one or more organization types. Click OK to save these changes, or Cancel to abandon them.", 
    "OPAC_VISIBLE": "OPAC sichtbar", 
    "ERROR_DELETING": "Problem beim L\u00f6schen von ${0}", 
    "ERROR_FETCHING_TYPES_AOUT": "Problem fetching organizational unit types", 
    "CONFIRM_DELETE": "Sind Sie sicher, dass sie ${0} l\u00f6schen m\u00f6chten?", 
    "ERROR_ORPHANS": "Cannot delete ${0}, ${1} subordinates still exist.", 
    "LABEL_DEPTH": "Depth", 
    "LABEL_NEW_TYPE": "New Type", 
    "LABEL_VALUE": "Value", 
    "SUCCESS_CREATING_CHILD_AOU": "New child Organizational Unit created for ${0}", 
    "EVENT_DEF_LABEL": "Copy text   \t ${0}: ${1}", 
    "ERROR_FETCHING_PHYSICAL": "Problem fetching Physical Address for ${0}", 
    "CONFIRM_EXIT_PPL": "There are unsaved modified permissions. Click OK to save these changes, or Cancel to abandon them.", 
    "ERROR_FETCHING_PERMS": "Problem fetching perms", 
    "LABEL_NEW_GROUP": "New Group", 
    "SUCCESS_SAVING_HOO": "Hours of Operation updated for ${0}", 
    "ERROR_SAVING_STATUS": "Problem beim Speichern von ${0}", 
    "ERROR_SAVING_PHYSICAL": "Problem saving Physical Address data for ${0}", 
    "CONFIRM_EXIT_AOU": "There are unsaved changes to one or more organizational units. Click OK to save these changes, or Cancel to abandon them.", 
    "ERROR_DELETING_PERM_MAPPING": "Problem deleting permission mapping ${0}", 
    "ERROR_SAVING_DATA_CAM": "Problem beim Speichern der Daten f\u00fcr ${0} ${1}", 
    "SUCCESS_SAVING_MAILING": "Saved changes to the Mailing Address of ${0}", 
    "ERROR_FETCHING_MAILING": "Problem fetching Mailing Address for ${0}", 
    "ACQ_DISTRIB_FORMULA_NAME_CLONE": "${0} (Clone)", 
    "ERROR_CREATING_CHILD_GROUP": "Problem creating child Group", 
    "ERROR_DELETING_LAST_AOU": "Cannot delete ${0}, you need at least one organization unit.", 
    "ERROR_SAVING_HOLDS": "Problem saving Holds Address data for ${0}", 
    "NAME": "Name", 
    "SUCCESS_CREATING_CHILD_AOUT": "New child Organization Type created for ${0}", 
    "LABEL_GRANTABLE": "Grantable", 
    "ERROR_SAVING_ILL": "Problem saving ILL Address data for ${0}", 
    "SURVEY_FOOT_LABEL": "Fragen und Antworten", 
    "ERROR_FETCHING_GROUPS": "Problem fetching groups", 
    "SUCCESS_CREATING_PERMISSION": "New ${0} permission created", 
    "SURVEY_ID": "Survey ID # ${0}", 
    "ERROR_CREATING_PERM_MAP": "Problem creating new Permission Map", 
    "SURVEY_DELETE_ANSWER": "Antwort l\u00f6schen", 
    "SURVEY_QUESTION": "Frage:", 
    "CONFIRM_EXIT_CAM": "There are unsaved changes to one or more ${0} codes. Click OK to save these changes, or Cancel to abandon them.", 
    "ERROR_DELETING_LAST_AOUT": "Cannot delete ${0}. You need at least one organization type.", 
    "ERROR_FETCHING_ILL": "Problem fetching ILL Address for ${0}", 
    "ERROR_CREATING_CHILD_AOUT": "Problem creating child organization type", 
    "ERROR_CALLING_METHOD_PGT": "Problem calling method to create child Group", 
    "CONFIRM_EXIT_PGT": "There are unsaved modified permission maps. Click OK to save these changes, or Cancel to abandon them.", 
    "SURVEY_ANSWER": "Antwort:", 
    "ERROR_FETCHING_PERM_MAPS": "Problem fetching perm maps", 
    "SURVEY_SAVE_ADD": "Frage speichern und Antwort hinzuf\u00fcgen", 
    "SUCCESS_SAVE": "\u00c4nderungen an ${0} gespeichert", 
    "ERROR_CALLING_METHOD_PERM_MAP": "Problem calling method to create new permission map", 
    "LABEL_CODE": "Code", 
    "SURVEY_DELETE_QUESTION": "Fragen und Antworten l\u00f6schen", 
    "SUCCESS_SAVE_PERM": "Saved permission changes to ${0}", 
    "SURVEY_ADD_ANSWER": "Antwort hinzuf\u00fcgen", 
    "ERROR_FETCHING_STATUSES": "Problem fetching statuses", 
    "ID": "ID", 
    "ERROR_CALLING_METHOD_CAM": "Problem calling method to create new ${0}", 
    "ERROR_SAVING_MAILING": "Problem saving Mailing Address data for ${0}", 
    "ERROR_CALLING_METHOD_AOUT": "Problem calling method to create child organization type", 
    "ERROR_CREATING_STATUS": "Problem creating new Status", 
    "SUCCESS_NEW_CHILD_GROUP": "New child Group created for ${0}"
}