{
    "SOURCE_SETUP_ALL_AVAIL_SOURCES": "Todas Fontes Dispon\u00edveis", 
    "TEMPLATE_CONF_SELECT_CANCEL": "Selecione o valor, ou cancele:", 
    "OPERATORS_ILIKE": "cont\u00e9m os subtextos iguais ao fornecido (ignorando mai\u00fasculas e min\u00fasculas)", 
    "FILTERS_LABEL_NULL_BLANK": "\u00c9 NULO ou Branco", 
    "OPERATORS_LIKE": "cont\u00e9m os subtextos iguais ao fornecido", 
    "WIDGET_MONTHS": "M\u00eas(es)", 
    "LINK_NULLABLE_RIGHT": "Pai", 
    "TFORMS_LABEL_AVERAGE": "M\u00e9dia", 
    "TEMPLATE_CONF_CONFIRM_STATE": "Clique OK para VERDADEIRO ou Cancelar para FALSO", 
    "OPERATORS_EQUALS": "Iguais", 
    "FILTERS_LABEL_BETWEEN": "Entre", 
    "OPERATORS_IN_LIST": "Na lista", 
    "TEMPLATE_CONF_NOT_IN": "Campo \u00e9 diferente a algum da lista (separados por virgulas):", 
    "OPERATORS_NOT_IN_LIST": "Fora da lista", 
    "FILTERS_LABEL_NOT_IN": "Fora da lista", 
    "SOURCE_BROWSE_NON_AGGREGATE": "N\u00e3o-Agregado", 
    "FILTERS_LABEL_GT_TIME": "Depois (Data/Hora)", 
    "OPERATORS_IS_NULL": "\u00c9 Nulo", 
    "TEMPLATE_CONF_CONFIRM_SAVE": "Nome : ${0}\nDescri\u00e7\u00e3o: ${1}\nSalvar Modelo?", 
    "OPERATORS_IS_NOT_NULL": "N\u00e3o \u00e9 NULO", 
    "TEMPLATE_CONF_CONFIRM_RESET": "Voc\u00ea j\u00e1 incluiu o campo [${0}]\nda fonte [${1}]. Clique OK se voc\u00ea\ndeseja redefinir este campo.", 
    "OPERATORS_GT_EQUAL": "Maior ou igual a", 
    "TRANSFORMS_MONTH_TRUNC": "Ano + M\u00eas", 
    "FILTERS_LABEL_NULL": "\u00c9 Nulo", 
    "REPORT_EDITOR_PROVIDE_FOLDER_ALERT": "Por favor informe a pasta para o relat\u00f3rio", 
    "OPERATORS_GT_TIME": "Depois (Data/Hora)", 
    "TRANSFORMS_YEAR_TRUNC": "Ano", 
    "TRANSFORMS_UPPER": "Mai\u00fasculas", 
    "FOLDERS_REPORTS": "Relat\u00f3rios", 
    "LINK_NULLABLE_LEFT": "Crian\u00e7a", 
    "TRANSFORMS_COUNT_DISTINCT": "Qtde de Distintos", 
    "FOLDER_WINDOW_COLNAME_SELECT": "Selecione", 
    "TRANSFORMS_FIRST": "Primeiro Valor", 
    "TFORMS_LABEL_LOWER": "Min\u00fasculas", 
    "TFORMS_LABEL_COUNT": "Qtde", 
    "TRANSFORMS_HOD": "Hora do dia", 
    "WIDGET_RELATIVE_DATE": "Data Relativa", 
    "FILTERS_LABEL_LESS_THAN": "Menor que", 
    "TEMPLATE_CONF_SUCCESS_SAVE": "O modelo ${0} foi salvo com sucesso.", 
    "TFORMS_LABEL_MOY": "M\u00eas do Ano", 
    "FILTERS_LABEL_EQ_ANY": "Iguais a Qualquer", 
    "TRANSFORMS_MAX": "M\u00e1x", 
    "TRANSFORMS_MIN": "Min", 
    "TRANSFORMS_SUM": "Soma", 
    "TRANSFORMS_FIRST_WORD": "Primeira sequ\u00eancia contigua de caracteres sem espa\u00e7o", 
    "TRANSFORMS_MONTHS_AGO": "Meses atr\u00e1s", 
    "SOURCE_BROWSE_AGGREGATE": "Agregar", 
    "TFORMS_LABEL_DATE": "Data", 
    "WIDGET_YEARS": "Ano(s)", 
    "FILTERS_LABEL_LT_TIME": "Antes (Data/Hora)", 
    "TRANSFORMS_COUNT": "Qtde", 
    "WIDGET_REAL_DATE": "Data Real", 
    "OPERATORS_LT_TIME": "Antes (Data/Hora)", 
    "TFORMS_LABEL_MAX": "M\u00e1x", 
    "TEMPLATE_CONF_FALSE": "Falso", 
    "TEMPLATE_CONF_BARE": "Puro", 
    "TRANSFORMS_LAST": "\u00daltimo Valor", 
    "TFORMS_LABEL_MIN": "Min", 
    "REPORT_EDITOR_REPORT_FOLDERS": "Pastas de Relat\u00f3rio", 
    "TEMPLATE_CONF_EQUALS": "Iguais", 
    "REPORT_EDITOR_OUTPUT_FOLDERS": "Pastas de grava\u00e7\u00e3o", 
    "FILTERS_LABEL_NOT_BETWEEN": "N\u00e3o Dentre", 
    "TRANSFORMS_QOY": "Quadrimestre", 
    "REPORT_EDITOR_PROVIDE_OUTPUT_ALERT": "Por favor informa uma pasa para grava\u00e7\u00e3o", 
    "FILTERS_LABEL_GREATER_THAN": "Maior do que", 
    "FILTERS_LABEL_NE_ANY": "N\u00e3o \u00e9 igual a nenhum", 
    "FOLDERS_OUTPUT": "Gravar em", 
    "OPERATORS_NE_ANY": "N\u00e3o \u00e9 igual a nenhum", 
    "TRANSFORMS_AVERAGE": "M\u00e9dia", 
    "FOLDERS_TEMPLATES": "Modelos", 
    "TFORMS_LABEL_DAY_NAME": "Nome do Dia", 
    "WIDGET_DAYS": "Dia(s)", 
    "TRANSFORMS_ROUND": "Arredondamento", 
    "FOLDERS_TEMPLATE": "Modelo", 
    "TRANSFORMS_HOUR_TRUNC": "Hora", 
    "TFORMS_LABEL_HOUR_TRUNC": "Hora", 
    "TRANSFORMS_MOY": "M\u00eas do Ano", 
    "LINK_NULLABLE_NONE": "Nenhum", 
    "RPT_BUILDER_CONFIRM_SAVE": "Nome : ${0}\nDescri\u00e7\u00e3o: ${1}\nSalvar Modelo?", 
    "TFORMS_LABEL_DOY": "Dia do Ano", 
    "TRANSFORMS_DATE": "Data", 
    "FOLDERS_REPORT": "Relat\u00f3rio", 
    "TFORMS_LABEL_DOW": "Dia da Semana", 
    "FILTERS_LABEL_LT_EQUAL": "Menor ou igual a", 
    "TFORMS_LABEL_INT": "Descarta decimais", 
    "OPERATORS_GTE_TIME": "Dentro ou ap\u00f3s (Data/Hora)", 
    "TFORMS_LABEL_DOM": "Dia do M\u00eas", 
    "FOLDER_WINDOW_COLNAME_NONE": "Nenhum", 
    "REPORT_EDITOR_ENTER_NAME_ALERT": "Por favor entre com o nome do relat\u00f3rio", 
    "OPERATORS_LT_EQUAL": "Menor ou igual a", 
    "TFORMS_LABEL_MONTHS_AGO": "Meses atr\u00e1s", 
    "TFORMS_LABEL_FIRST_WORD": "Primeira sequ\u00eancia contigua de caracteres sem espa\u00e7o", 
    "FOLDER_WINDOW_REPORT_OUTPUT": "Relat\u00f3rio Gravado: {0}", 
    "FILTERS_LABEL_GTE_TIME": "Dentro ou ap\u00f3s (Data/Hora)", 
    "TFORMS_LABEL_FIRST": "Primeiro Valor", 
    "TRANSFORMS_AGE": "Idade/Tempo", 
    "FILTERS_LABEL_LIKE": "cont\u00e9m os subtextos iguais ao fornecido", 
    "TEMPLATE_CONF_TRUE": "Verdadeiro", 
    "SOURCE_SETUP_CONFIRM_EXIT": "Voc\u00ea iniciou a cria\u00e7\u00e3o de um modelo!\n Ao selecionar uma nova fonte ser\u00e1 destru\u00eddo o modelo atual e come\u00e7ar\u00e1 novamente. \u00c9 isto que DESEJA?", 
    "TRANSFORMS_QUARTERS_AGO": "Quadrimestres atr\u00e1s", 
    "TFORMS_LABEL_MONTH_TRUNC": "Ano + M\u00eas", 
    "TEMPLATE_CONF_IN": "Campo \u00e9 igual a algum da lista (separados por virgulas):", 
    "FILTERS_LABEL_ILIKE": "cont\u00e9m os subtextos iguais ao fornecido (ignorando mai\u00fasculas e min\u00fasculas)", 
    "FILTERS_LABEL_NOT_NULL": "N\u00e3o \u00e9 NULO", 
    "TEMPLATE_CONF_NO_MATCH": "Campo \u00e9 diferente a algum da lista (separados por virgulas):", 
    "TFORMS_LABEL_UPPER": "Mai\u00fasculas", 
    "TRANSFORMS_SUBSTRING": "Subtexto", 
    "FILTERS_LABEL_GT_EQUAL": "Maior ou igual a", 
    "TEMPLATE_CONF_RAW_DATA": "Dados puros", 
    "TFORMS_LABEL_HOD": "Hora do dia", 
    "FILTERS_LABEL_NOT_NULL_BLANK": "N\u00e3o \u00e9 NULO ou Branco", 
    "TFORMS_LABEL_SUM": "Soma", 
    "LINK_NULLABLE_DEFAULT": "Default", 
    "FILTERS_LABEL_IN": "Na lista", 
    "TFORMS_LABEL_AGE": "Idade/Tempo", 
    "FOLDER_WINDOW_CHANGE_FOLDERS": "Alterar senha", 
    "TRANSFORMS_LOWER": "Min\u00fasculas", 
    "TRANSFORMS_MONTH_NAME": "Nome do M\u00eas", 
    "TRANSFORMS_DOW": "Dia da Semana", 
    "TEMPLATE_CONF_PROMPT_CHANGE": "Alterar o cabe\u00e7alho da coluna para: $(0)", 
    "OPERATORS_NOT_BETWEEN": "N\u00e3o Dentre", 
    "TRANSFORMS_DOY": "Dia do Ano", 
    "REPORT_EDITOR_INVALID_DATE_ALERT": "data de in\u00edcio inv\u00e1lida - AAAA-MM-DD", 
    "TRANSFORMS_BARE": "Dados puros", 
    "TRANSFORMS_DOM": "Dia do M\u00eas", 
    "TFORMS_LABEL_MONTH_NAME": "Nome do M\u00eas'", 
    "OPERATORS_EQ_ANY": "Iguais a Qualquer", 
    "TFORMS_LABEL_ROUND": "Arredondamento", 
    "OPERATORS_GREATER_THAN": "Maior do que", 
    "SOURCE_SETUP_CORE_SOURCES": "Fontes Principais", 
    "TFORMS_LABEL_LAST": "\u00daltimo Valor", 
    "FILTERS_LABEL_EQUALS": "Iguais", 
    "FOLDER_WINDOW_COLNAME_ALL": "Tudo", 
    "TFORMS_LABEL_RAW_DATA": "Dados puros", 
    "TFORMS_LABEL_COUNT_DISTINCT": "Qtde de Distintos", 
    "TFORMS_LABEL_FIRST5": "Primeiros 5 caracteres (para CEP)", 
    "TEMPLATE_CONF_NOT_BETWEEN": "Valor do campo n\u00e3o esta entre (separado por virgula):", 
    "TRANSFORMS_INT": "Descarta decimais", 
    "FILTERS_LABEL_LSE_TIME": "Dentro ou Antes (Data/Hora)", 
    "TRANSFORMS_DAY_NAME": "Nome do Dia", 
    "FOLDER_WINDOW_SELECT_ITEM": "Por favor selecione um item da lista", 
    "TRANSFORMS_FIRST5": "Primeiros 5 caracteres (para CEP)", 
    "OPERATORS_LTE_TIME": "Dentro ou Antes (Data/Hora)", 
    "TEMPLATE_CONF_DEFAULT": "Valor ${0}:", 
    "TFORMS_LABEL_YEAR_TRUNC": "Ano", 
    "TRANSFORMS_WOY": "Semana do Ano", 
    "TFORMS_LABEL_WOY": "Semana do Ano", 
    "TFORMS_LABEL_QUARTERS_AGO": "Quadrimestres atr\u00e1s", 
    "TEMPLATE_CONF_BOOLEAN_VALUE": "Valor boleano", 
    "OPERATORS_NOT_NULL_BLANK": "N\u00e3o \u00e9 NULO ou Branco", 
    "OPERATORS_NULL_BLANK": "\u00c9 NULO ou Branco", 
    "TEMPLATE_CONF_BETWEEN": "Valor do campo esta entre (separado por virgula):", 
    "TFORMS_LABEL_QOY": "Quadrimestre", 
    "WIDGET_QUARTERS": "Quadrimestre(s)", 
    "OPERATORS_LESS_THAN": "Menor que", 
    "OPERATORS_BETWEEN": "Entre"
}