{
    "ONLINE_VOLUMES": "Online volumes", 
    "CREATED_MFHD_RECORD": "Created MFHD record for ${0}", 
    "EDIT_PROPERTIES": "Editovat vlastnosti", 
    "HOLDINGS_TABLE_CAPTION": "Holdings summary (${0})", 
    "CURRENT_INDEXES": "Current indexes", 
    "CURRENT_HOLDINGS": "Moment\u00e1ln\u00ed hlasitost", 
    "INCOMPLETE_VOLUMES": "Incomplete volumes", 
    "EDIT_MFHD_MENU": "Edit Holdings", 
    "INDEXES": "Previous indexes", 
    "HOLDINGS": "Previous volumes", 
    "EDIT_MFHD_RECORD": "Editovat z\u00e1znam", 
    "SUPPLEMENTS": "Previous supplements", 
    "CREATE_MFHD": "P\u0159idat MFHD z\u00e1znam", 
    "SAVE_MFHD_LABEL": "Ulo\u017eit MFHD", 
    "CURRENT_SUPPLEMENTS": "Current supplements", 
    "MISSING_VOLUMES": "Missing volumes", 
    "DELETE_MFHD": "Delete Record", 
    "DELETED_MFHD_RECORD": "Deleted MFHD record ${0}"
}