{
    "ONLINE_VOLUMES": "Vol\u00famenes en l\u00ednea", 
    "CREATED_MFHD_RECORD": "Se cre\u00f3 un registro MFHD para ${0}", 
    "EDIT_PROPERTIES": "Editar propiedades", 
    "HOLDINGS_TABLE_CAPTION": "Resumen de Explotaciones o Particiones (${0})", 
    "CURRENT_INDEXES": "\u00cdndices actuales", 
    "CURRENT_HOLDINGS": "Volumen actual", 
    "INCOMPLETE_VOLUMES": "Vol\u00famenes Incompletos", 
    "EDIT_MFHD_MENU": "Editar Explotaciones", 
    "INDEXES": "\u00cdndices previos", 
    "HOLDINGS": "Vol\u00famenes previos", 
    "EDIT_MFHD_RECORD": "Editar registro", 
    "SUPPLEMENTS": "Suplementos previos", 
    "CREATE_MFHD": "A\u00f1adir registro MFFHD", 
    "SAVE_MFHD_LABEL": "Guardar MFHD", 
    "CURRENT_SUPPLEMENTS": "Suplementos actuales", 
    "MISSING_VOLUMES": "Vol\u00famenes faltantes", 
    "DELETE_MFHD": "Eliminar registro", 
    "DELETED_MFHD_RECORD": "Eliminar registro MFHD ${0}"
}