{
    "PWD_RESET_SUBMIT_ERROR": "The system could not process your request for a password reset. Please try again, or contact circulation staff for assistance.", 
    "PWD_RESET_SUBMIT_SUCCESS": "Your request to begin the password reset process has been processed. If your account has a valid email address, you should soon receive an email containing further instructions for resetting your password.", 
    "USERNAME_PROMPT": "User name: ", 
    "HOLD_STATUS_PLURAL": "hold # ${0} of ${1} total holds and ${2} potential items", 
    "HOLDINGS_TABLE_CAPTION": "V\u00fdsledek hospod\u00e1\u0159stv\u00ed (${0})", 
    "INDEX_HOLDINGS": "Indexes", 
    "EDIT_MFHD_RECORD": "Editovat z\u00e1znam", 
    "MISSING_VOLUMES": "Sch\u00e1zej\u00edc\u00ed objemy", 
    "DELETED_MFHD_RECORD": "Smazan\u00e1 MFHD nahr\u00e1vka pro ${0}", 
    "SUBMIT_BUTTON_LABEL": "Submit", 
    "CREATED_MFHD_RECORD": "Vytvo\u0159en\u00e1 MFHD nahr\u00e1vka pro ${0}", 
    "CURRENT_INDEXES": "Aktu\u00e1ln\u00ed p\u0159\u00edznaky", 
    "BARCODE_PROMPT": "Barcode: ", 
    "PWD_RESET_RESPONSE_TITLE": "Password reset response", 
    "CURRENT_SUPPLEMENTS": "Aktu\u00e1ln\u00ed dop\u0148ky", 
    "ONLINE_VOLUMES": "Online obsahy", 
    "DELETE_MFHD": "Smazat z\u00e1znam", 
    "CREATE_MFHD": "P\u0159idat MFHD z\u00e1znam", 
    "EDIT_PROPERTIES": "Editovat vlastnosti", 
    "CANCEL_BUTTON_LABEL": "Cancel", 
    "CURRENT_HOLDINGS": "Moment\u00e1ln\u00ed hlasitost", 
    "MORE_COPIES_FULL_RECORD": "... more copies listed in full record", 
    "SUPPLEMENT_HOLDINGS_ADD": "Additional Supplement Information", 
    "INCOMPLETE_VOLUMES": "Mekompletn\u00ed objemy", 
    "SAVE_MFHD_LABEL": "Ulo\u017eit MFHD", 
    "OK": "OK", 
    "INDEX_HOLDINGS_ADD": "Additional Index Information", 
    "PWD_RESET_FORGOT_PROMPT": "Forgot your password?", 
    "PWD_RESET_FORM_TITLE": "Request password reset", 
    "PWD_RESET_SUBMIT_PROMPT": "To begin the password reset process, enter either your barcode or user name in the form below and click 'Submit'", 
    "HOLD_STATUS_SINGULAR": "hold # ${0} of ${1} total holds and ${2} potential item", 
    "PWD_RESET_SUBMIT_STATUS": "Sending request...", 
    "DELETE_MFHD_CONFIRM": "Are you sure you want to delete this serial record?", 
    "PLACE_HOLD": "Place hold", 
    "BASIC_HOLDINGS": "Volumes", 
    "EDIT_MFHD_MENU": "Upravit hospod\u00e1\u0159stv\u00ed", 
    "BASIC_HOLDINGS_ADD": "Additional Volume Information", 
    "SUPPLEMENT_HOLDINGS": "Supplements", 
    "MORE": "More"
}