{
    "WORKSTATION_EXISTS": "This workstation has already been registered.  Would you like to use it for this self-check station?", 
    "FAIL_PART_no_item": "The system could not find this item", 
    "HOLD_STATUS_WAITING": "#${0} in line with ${1} copies", 
    "OPEN_CIRCULATION_EXISTS": "Item ${0} is already checked out to another user", 
    "RENEW_SUCCESS": "Renewal of item ${0} succeeded", 
    "FAIL_PART_config_rule_age_hold_protect_prox": "The item is too new to transit this far", 
    "FAIL_PART_asset_copy_circulate": "The item does not circulate", 
    "FAIL_PART_config_hold_matrix_test_max_holds": "The patron has reached the maximum number of holds", 
    "CHECKOUT_SUCCESS": "Checkout of item ${0} succeeded", 
    "ALREADY_OUT": "Item ${0} is already checked out", 
    "TOTAL_FINES_ACCOUNT": "Total fines on account: <b>$${0}</b>.", 
    "FAIL_PART_transit_range": "The item cannot transit this far", 
    "FAIL_PART_config_circ_matrix_test_available_copy_hold_ratio": "The available item-to-hold ratio is too low", 
    "TOTAL_ITEMS_SESSION": "Total items this session: <b>${0}</b>.", 
    "FAIL_PART_config_hold_matrix_test_holdable": "Hold rules reject this item as unholdable", 
    "FAIL_PART_circ_holds_target_skip_me": "The item's circulation library does not fulfill holds", 
    "TOTAL_FINES_SELECTED": "Selected total: $${0}", 
    "FAIL_PART_no_matchpoint": "System rules do not define how to handle this item", 
    "ITEM_NOT_CATALOGED": "Item ${0} was not found in the system.  Try re-scanning the item.", 
    "TOTAL_HOLDS": "You have <b>${0}</b> total holds.", 
    "FAIL_PART_asset_copy_location_circulate": "Items from this shelving location do not circulate", 
    "FAIL_PART_no_ultimate_items": "The system could not find any items to match this hold request", 
    "FAIL_PART_asset_copy_status": "The item cannot circulate at this time", 
    "UNKNOWN_ERROR": "An unhandled exception occurred with error code ${0}", 
    "CC_PAYABLE_BALANCE": "Total amount to pay: $${0}", 
    "WELCOME_BANNER": "Welcome, ${0}", 
    "LOGIN_FAILED": "Login for ${0} failed", 
    "GENERIC_CIRC_FAILURE": "Unable to check out item ${0}.  Please see staff.", 
    "MAX_RENEWALS": "No more renewals allowed for item ${0}", 
    "FAIL_PART_config_circ_matrix_test_total_copy_hold_ratio": "The total item-to-hold ratio is too low", 
    "HOLDS_READY_FOR_PICKUP": "You have <b>${0}</b> item(s) ready for pickup.", 
    "FAIL_PART_actor_usr_barred": "The patron is barred", 
    "WORKSTATION_REQUIRED": "A workstation is required to log in to selfcheck.  You can set the  workstation name with URL param 'ws'.  \n\nWould you like to register a new workstation for this self-check interface?", 
    "TOTAL_ITEMS_ACCOUNT": "Total items on account:  <b>${0}</b>.", 
    "FAIL_PART_no_user": "The system could not find this patron", 
    "HOLD_STATUS_READY": "Ready for pickup", 
    "FAIL_PART_config_circ_matrix_circ_mod_test": "The patron has too many items of this type checked out", 
    "PAYMENT_INVALID_USER_XACT_ID": "We cannot proceed with the payment, because your account was updated from another location.  Please refresh the interface or log out and back in to retrieve the latest account information", 
    "FAIL_PART_config_circ_matrix_test_circulate": "Circulation rules reject this item as non-circulatable"
}