{
    "and": "AND", 
    "sort": "Sort Axis", 
    "bib_level": "Bibliographic Level", 
    "less": "...Less", 
    "item_form": "Form", 
    "site": "Site", 
    "filters": "Filters", 
    "notcontains": "Does Not Contain", 
    "statuses": "Statuses", 
    "before": "Published Before", 
    "new_facet": "New Facet", 
    "lit_form": "Literary Form", 
    "faceted_searches": "Facets", 
    "contains": "Contains", 
    "audience": "Audience", 
    "filter_default": "-- Select a Filter --", 
    "metabib": "Metarecord Search", 
    "basic": "Basic", 
    "new_modifier": "New Modifier", 
    "staff": "Staff Search", 
    "classed_searches": "Classed Searches", 
    "more": "More...", 
    "available": "Available", 
    "new_filter": "New Filter", 
    "format": "Type and Form", 
    "after": "Published After", 
    "ascending": "Sort Ascending", 
    "descending": "Sort Descending", 
    "modifier_default": "-- Select a Modifier --", 
    "during": "In Publication", 
    "exact": "Exactly Matches", 
    "between": "Published Between", 
    "advanced": "Advanced", 
    "modifiers": "Modifiers", 
    "perform_search": "Go!", 
    "remove": "Remove", 
    "item_type": "Type", 
    "depth": "Search Depth", 
    "vr_format": "Videorecording Format", 
    "or": "OR"
}