{
    "SOURCE_SETUP_ALL_AVAIL_SOURCES": "Todas las fuentes disponibles", 
    "TEMPLATE_CONF_SELECT_CANCEL": "Seleccione el valor, o cancelar:", 
    "OPERATORS_ILIKE": "Contiene subcadena coincidente (ignorar may\u00fasculas)", 
    "FILTERS_LABEL_NULL_BLANK": "Es NULL \u00f3 vac\u00edo", 
    "OPERATORS_LIKE": "Contiene subcadena coincidente", 
    "WIDGET_MONTHS": "Mes(es)", 
    "LINK_NULLABLE_RIGHT": "Padres", 
    "TFORMS_LABEL_AVERAGE": "Promedio", 
    "TEMPLATE_CONF_CONFIRM_STATE": "Click en OK para VERDADERO o en Cancelar para FALSO.", 
    "OPERATORS_EQUALS": "Igual a", 
    "FILTERS_LABEL_BETWEEN": "Entre", 
    "OPERATORS_IN_LIST": "En la lista", 
    "TEMPLATE_CONF_NOT_IN": "Campo no coincide con ninguno de la lista (separados por coma):", 
    "OPERATORS_NOT_IN_LIST": "No est\u00e1 en la lista", 
    "FILTERS_LABEL_NOT_IN": "No est\u00e1 en la lista", 
    "SOURCE_BROWSE_NON_AGGREGATE": "No Agregados", 
    "FILTERS_LABEL_GT_TIME": "Despu\u00e9s de (Fecha/Hora)", 
    "OPERATORS_IS_NULL": "Es NULL", 
    "TEMPLATE_CONF_CONFIRM_SAVE": "Nombre : ${0}\nDescripci\u00f3n: ${1}\n\u00bfGuardar plantilla?", 
    "OPERATORS_IS_NOT_NULL": "No es NULL", 
    "TEMPLATE_CONF_CONFIRM_RESET": "Ya agreg\u00f3 el campo [${0}]\ndesde la fuente [${1}]. Click en\nOK s\u00ed desea reiniciar el campo.", 
    "OPERATORS_GT_EQUAL": "Mayor o igual a", 
    "TRANSFORMS_MONTH_TRUNC": "A\u00f1o + Mes", 
    "FILTERS_LABEL_NULL": "Es NULL", 
    "REPORT_EDITOR_PROVIDE_FOLDER_ALERT": "Por favor provea una carpeta de informe", 
    "OPERATORS_GT_TIME": "Despu\u00e9s de (Fecha/Hora)", 
    "TRANSFORMS_YEAR_TRUNC": "A\u00f1o", 
    "TRANSFORMS_UPPER": "May\u00fasculas", 
    "FOLDERS_REPORTS": "Informes", 
    "LINK_NULLABLE_LEFT": "Hijo", 
    "TRANSFORMS_COUNT_DISTINCT": "Recuento distintivo", 
    "FOLDER_WINDOW_COLNAME_SELECT": "Seleccionar", 
    "TRANSFORMS_FIRST": "Primer valor", 
    "TFORMS_LABEL_LOWER": "Min\u00fasculas", 
    "TFORMS_LABEL_COUNT": "Contar", 
    "TRANSFORMS_HOD": "Hora del d\u00eda", 
    "WIDGET_RELATIVE_DATE": "Fecha relativa", 
    "FILTERS_LABEL_LESS_THAN": "Menor que", 
    "TEMPLATE_CONF_SUCCESS_SAVE": "La plantilla ${0} fue guardada correctamente.", 
    "TFORMS_LABEL_MOY": "Mes del a\u00f1o", 
    "FILTERS_LABEL_EQ_ANY": "Igual a cualquiera", 
    "TRANSFORMS_MAX": "M\u00e1x", 
    "TRANSFORMS_MIN": "M\u00edn", 
    "TRANSFORMS_SUM": "Suma", 
    "TRANSFORMS_FIRST_WORD": "Primera cadena contigua sin espacios", 
    "TRANSFORMS_MONTHS_AGO": "Hace meses", 
    "SOURCE_BROWSE_AGGREGATE": "Agregar", 
    "TFORMS_LABEL_DATE": "Fecha", 
    "WIDGET_YEARS": "A\u00f1o(s)", 
    "FILTERS_LABEL_LT_TIME": "Antes de (Fecha/Hora)", 
    "TRANSFORMS_COUNT": "Contar", 
    "WIDGET_REAL_DATE": "Fecha real", 
    "OPERATORS_LT_TIME": "Antes de (Fecha/Hora)", 
    "TFORMS_LABEL_MAX": "M\u00e1x", 
    "TEMPLATE_CONF_FALSE": "Falso", 
    "TEMPLATE_CONF_BARE": "Simple", 
    "TRANSFORMS_LAST": "\u00daltimo valor", 
    "TFORMS_LABEL_MIN": "M\u00edn", 
    "REPORT_EDITOR_REPORT_FOLDERS": "Carpetas de informes", 
    "TEMPLATE_CONF_EQUALS": "Igual a", 
    "REPORT_EDITOR_OUTPUT_FOLDERS": "Carpetas de salida", 
    "FILTERS_LABEL_NOT_BETWEEN": "No est\u00e9 entre", 
    "TRANSFORMS_QOY": "Cuarto de a\u00f1o", 
    "REPORT_EDITOR_PROVIDE_OUTPUT_ALERT": "Por favor provea una carpeta de salida", 
    "FILTERS_LABEL_GREATER_THAN": "Mayor que", 
    "FILTERS_LABEL_NE_ANY": "Es distinto de", 
    "FOLDERS_OUTPUT": "Salida", 
    "OPERATORS_NE_ANY": "Es distinto de", 
    "TRANSFORMS_AVERAGE": "Promedio", 
    "FOLDERS_TEMPLATES": "Plantillas", 
    "TFORMS_LABEL_DAY_NAME": "Nombre del d\u00eda", 
    "WIDGET_DAYS": "D\u00eda(s)", 
    "TRANSFORMS_ROUND": "Redondear", 
    "FOLDERS_TEMPLATE": "Plantilla", 
    "TRANSFORMS_HOUR_TRUNC": "Hora", 
    "TFORMS_LABEL_HOUR_TRUNC": "Hora", 
    "TRANSFORMS_MOY": "Mes del a\u00f1o", 
    "LINK_NULLABLE_NONE": "Ninguno", 
    "RPT_BUILDER_CONFIRM_SAVE": "Nombre : ${0}\nDescripci\u00f3n: ${1}\n\u00bfGuardar plantilla?", 
    "TFORMS_LABEL_DOY": "D\u00eda del a\u00f1o", 
    "TRANSFORMS_DATE": "Fecha", 
    "FOLDERS_REPORT": "Informe", 
    "TFORMS_LABEL_DOW": "D\u00eda de la semana", 
    "FILTERS_LABEL_LT_EQUAL": "Menor o igual a", 
    "TFORMS_LABEL_INT": "Descartar decimales", 
    "OPERATORS_GTE_TIME": "En o Despu\u00e9s (Fecha/Hora)", 
    "TFORMS_LABEL_DOM": "D\u00eda del mes", 
    "FOLDER_WINDOW_COLNAME_NONE": "Ninguno", 
    "REPORT_EDITOR_ENTER_NAME_ALERT": "Por favor ingrese un nombre de informe", 
    "OPERATORS_LT_EQUAL": "Menor o igual a", 
    "TFORMS_LABEL_MONTHS_AGO": "Hace meses", 
    "TFORMS_LABEL_FIRST_WORD": "Primera cadena contigua sin espacios", 
    "FOLDER_WINDOW_REPORT_OUTPUT": "Informe de salida: ${0}", 
    "FILTERS_LABEL_GTE_TIME": "En o Despu\u00e9s (Fecha/Hora)", 
    "TFORMS_LABEL_FIRST": "Primer valor", 
    "TRANSFORMS_AGE": "Edad", 
    "FILTERS_LABEL_LIKE": "Contiene subcadena coincidente", 
    "TEMPLATE_CONF_TRUE": "Verdadero", 
    "SOURCE_SETUP_CONFIRM_EXIT": "\u00a1Usted ha comenzado a crear una plantilla!\n Seleccionar una nueva fuente de inicio destruir\u00e1 la plantilla actual y tendr\u00e1 que volver a empezar. \u00bfEst\u00e1 de acuerdo?", 
    "TRANSFORMS_QUARTERS_AGO": "trimestres atr\u00e1s", 
    "TFORMS_LABEL_MONTH_TRUNC": "A\u00f1o + Mes", 
    "TEMPLATE_CONF_IN": "Campo coincide con uno de la lista (separados por coma):", 
    "FILTERS_LABEL_ILIKE": "Contiene subcadena coincidente (ignorar may\u00fasculas)", 
    "FILTERS_LABEL_NOT_NULL": "No es NULL", 
    "TEMPLATE_CONF_NO_MATCH": "Campo no coincide con ninguno de la lista (separados por coma):", 
    "TFORMS_LABEL_UPPER": "May\u00fasculas", 
    "TRANSFORMS_SUBSTRING": "Subcadena", 
    "FILTERS_LABEL_GT_EQUAL": "Mayor o igual a", 
    "TEMPLATE_CONF_RAW_DATA": "Datos en crudo", 
    "TFORMS_LABEL_HOD": "Hora del d\u00eda", 
    "FILTERS_LABEL_NOT_NULL_BLANK": "No es NULL o vac\u00edo", 
    "TFORMS_LABEL_SUM": "Suma", 
    "LINK_NULLABLE_DEFAULT": "Predeterminado", 
    "FILTERS_LABEL_IN": "En la lista", 
    "TFORMS_LABEL_AGE": "Edad", 
    "FOLDER_WINDOW_CHANGE_FOLDERS": "Cambiar carpetas", 
    "TRANSFORMS_LOWER": "Min\u00fasculas", 
    "TRANSFORMS_MONTH_NAME": "Nombre del mes", 
    "TRANSFORMS_DOW": "D\u00eda de la semana", 
    "TEMPLATE_CONF_PROMPT_CHANGE": "Cambiar el encabezado de la columna a: ${0}", 
    "OPERATORS_NOT_BETWEEN": "No est\u00e9 entre", 
    "TRANSFORMS_DOY": "D\u00eda del a\u00f1o", 
    "REPORT_EDITOR_INVALID_DATE_ALERT": "fecha inicia inv\u00e1lida -  YYYY-MM-DD", 
    "TRANSFORMS_BARE": "Datos en crudo", 
    "TRANSFORMS_DOM": "D\u00eda del mes", 
    "TFORMS_LABEL_MONTH_NAME": "Nombre del mes'", 
    "OPERATORS_EQ_ANY": "Igual a cualquiera", 
    "TFORMS_LABEL_ROUND": "Redondear", 
    "OPERATORS_GREATER_THAN": "Mayor que", 
    "SOURCE_SETUP_CORE_SOURCES": "Fuentes centrales", 
    "TFORMS_LABEL_LAST": "\u00daltimo valor", 
    "FILTERS_LABEL_EQUALS": "Igual a", 
    "FOLDER_WINDOW_COLNAME_ALL": "Todos", 
    "TFORMS_LABEL_RAW_DATA": "Datos en crudo", 
    "TFORMS_LABEL_COUNT_DISTINCT": "Recuento distintivo", 
    "TFORMS_LABEL_FIRST5": "Primeros 5 caracteres (para c\u00f3digos postales de EEUU)", 
    "TEMPLATE_CONF_NOT_BETWEEN": "Valor de campo no est\u00e1 entre (separados por coma):", 
    "TRANSFORMS_INT": "Descartar decimales", 
    "FILTERS_LABEL_LSE_TIME": "En o Antes (Fecha/Hora)", 
    "TRANSFORMS_DAY_NAME": "Nombre del d\u00eda", 
    "FOLDER_WINDOW_SELECT_ITEM": "Por favor seleccione un elemento de la lista", 
    "TRANSFORMS_FIRST5": "Primeros 5 caracteres (para c\u00f3digos postales de EEUU)", 
    "OPERATORS_LTE_TIME": "En o Antes (Fecha/Hora)", 
    "TEMPLATE_CONF_DEFAULT": "Valor ${0}:", 
    "TFORMS_LABEL_YEAR_TRUNC": "A\u00f1o", 
    "TRANSFORMS_WOY": "Semana del a\u00f1o", 
    "TFORMS_LABEL_WOY": "Semana del a\u00f1o", 
    "TFORMS_LABEL_QUARTERS_AGO": "trimestres atr\u00e1s", 
    "TEMPLATE_CONF_BOOLEAN_VALUE": "Valor booleano", 
    "OPERATORS_NOT_NULL_BLANK": "No es NULL o vac\u00edo", 
    "OPERATORS_NULL_BLANK": "Es NULL \u00f3 vac\u00edo", 
    "TEMPLATE_CONF_BETWEEN": "El valor del campo est\u00e1 entre (separados por comas):", 
    "TFORMS_LABEL_QOY": "Cuarto de a\u00f1o", 
    "WIDGET_QUARTERS": "Cuarto(s)", 
    "OPERATORS_LESS_THAN": "Menor que", 
    "OPERATORS_BETWEEN": "Entre"
}