{
    "PWD_RESET_SUBMIT_ERROR": "O sistema n\u00e3o pode processar seu pedido para restaurar a senha. Por favor, tente novamente ou contate o administrador ou respons\u00e1vel.", 
    "PWD_RESET_SUBMIT_SUCCESS": "O seu pedido para iniciar o processo de redefini\u00e7\u00e3o de senha foi processado. Se a sua conta de um e-mail \u00e9 v\u00e1lida, voc\u00ea dever\u00e1 em breve receber um email com mais instru\u00e7\u00f5es para redefinir sua senha.", 
    "USERNAME_PROMPT": "Nome do usu\u00e1rio: ", 
    "HOLD_STATUS_PLURAL": "hold # ${0} of ${1} total holds and ${2} potential items", 
    "HOLDINGS_TABLE_CAPTION": "S\u00famario de reservas (${0})", 
    "INDEX_HOLDINGS": "\u00cdndices", 
    "EDIT_MFHD_RECORD": "Editar Registro", 
    "MISSING_VOLUMES": "Volumes em falta", 
    "DELETED_MFHD_RECORD": "Excluir registro MFHD ${0}", 
    "SUBMIT_BUTTON_LABEL": "Enviar", 
    "CREATED_MFHD_RECORD": "Criar um registro MFHD para ${0}", 
    "CURRENT_INDEXES": "\u00cdndices atuais", 
    "BARCODE_PROMPT": "C\u00f3digo de Barras ", 
    "PWD_RESET_RESPONSE_TITLE": "Resposta de redefini\u00e7\u00e3o de senha", 
    "CURRENT_SUPPLEMENTS": "Suplementos Atuais", 
    "ONLINE_VOLUMES": "Volumes online", 
    "DELETE_MFHD": "Excluir Registro", 
    "CREATE_MFHD": "Incluir Registro  MFHD", 
    "EDIT_PROPERTIES": "Editar Propriedades", 
    "CANCEL_BUTTON_LABEL": "Cancelar", 
    "CURRENT_HOLDINGS": "Volume atual", 
    "MORE_COPIES_FULL_RECORD": "... more copies listed in full record", 
    "SUPPLEMENT_HOLDINGS_ADD": "Suplemento de Informa\u00e7\u00f5es adicionais", 
    "INCOMPLETE_VOLUMES": "Volumes incompletos", 
    "SAVE_MFHD_LABEL": "Salvar MFHD", 
    "OK": "OK", 
    "INDEX_HOLDINGS_ADD": "Informa\u00e7\u00e3o adicional de \u00edndice", 
    "PWD_RESET_FORGOT_PROMPT": "Esqueceu sua senha?", 
    "PWD_RESET_FORM_TITLE": "Pedido de redefini\u00e7\u00e3o de senha", 
    "PWD_RESET_SUBMIT_PROMPT": "Para iniciar o processo de redefini\u00e7\u00e3o de senha, digite seu nome ou c\u00f3digo de barras ou nome de usu\u00e1rio no formul\u00e1rio abaixo e clique em \"Enviar\"", 
    "HOLD_STATUS_SINGULAR": "hold # ${0} of ${1} total holds and ${2} potential item", 
    "PWD_RESET_SUBMIT_STATUS": "Enviando requisi\u00e7\u00e3o...", 
    "DELETE_MFHD_CONFIRM": "Tem certeza de que deseja excluir este registro serial?", 
    "PLACE_HOLD": "Place hold", 
    "BASIC_HOLDINGS": "Volumes", 
    "EDIT_MFHD_MENU": "Editar Reservas", 
    "BASIC_HOLDINGS_ADD": "Informa\u00e7\u00f5es sobre o volume adicional", 
    "SUPPLEMENT_HOLDINGS": "Suplementos", 
    "MORE": "More"
}