{
    "SUCCESS_SAVING_PHYSICAL": "Salvo altera\u00e7\u00f5es para o Endere\u00e7o F\u00edsico para $(0)", 
    "CONFIRM_EXIT_CCS": "Existem altera\u00e7\u00f5es n\u00e3o salvas para um ou mais situa\u00e7\u00f5es. Clique OK para salva-las, ou Cancelar para abandona-las.", 
    "SURVEY_SAVE_CHANGES": "Salvar Altera\u00e7\u00f5es", 
    "ERROR_CREATING_CHILD_AOU": "Problema ao criar unidade organizacional filha", 
    "ERROR_CALLING_METHOD_PPL": "Problema ao chamar m\u00e9todo para criar nova permiss\u00e3o", 
    "TRANSLATION": "Tradu\u00e7\u00e3o", 
    "ERROR_FETCHING_ORGS": "Problema ao obter dados de unidade organizacional", 
    "SUCCESS_CREATING_STATUS": "Nova ${0} situa\u00e7\u00e3o criada", 
    "SUCCESS_SAVING_HOLDS": "Salvo altera\u00e7\u00f5es para os Endere\u00e7os de Reservas para $(0)", 
    "SUCCESS_SAVING_ILL": "Salvo altera\u00e7\u00f5es para o Endere\u00e7o de ILL para $(0)", 
    "STATUS_EDITING": "Editando agora ${0}", 
    "SUCCESS_SAVING_DATA": "Salvo altera\u00e7\u00f5es para $(0)", 
    "SUCCESS_DELETED_PERM_MAP": "Mapa de permiss\u00e3o exclu\u00eddo", 
    "ERROR_SAVING_PERM_DATA": "Problema ao salvar dados de permiss\u00e3o para $(0)", 
    "ERROR_FETCHING_HOLDS": "Problema ao obter Endere\u00e7os de Reservas para $(0)", 
    "HOLDABLE": "Reserv\u00e1vel", 
    "STATUS_DELETED": "${0} exclu\u00eddo(s)", 
    "ERROR_CALLING_METHOD_CCS": "Problema ao chamar m\u00e9todo para criar nova situa\u00e7\u00e3o de exemplar", 
    "SUCCESS_CREATING_CODE": "Novo(a) ${0} ${1} criado", 
    "ACQ_DISTRIB_FORMULA_NAME_PROMPT": "Enter new formula name", 
    "ERROR_SAVING_DATA": "Problema ao salvar dados para $(0)", 
    "LABEL_NEW_BRANCH": "Nova Ramifica\u00e7\u00e3o", 
    "ERROR_FETCHING_HOURS": "Problema ao obter as horas em opera\u00e7\u00e3o para $(0)", 
    "LABEL_TRANSLATION": "Tradu\u00e7\u00e3o", 
    "ERROR_CREATING_PERMISSION": "Problema ao criar nova Permiss\u00e3o", 
    "LABEL_DESCRIPTION": "Descri\u00e7\u00e3o", 
    "ERROR_SAVING_HOO": "Problema ao salvar dados de Horas em Opera\u00e7\u00e3o para $(0)", 
    "SUCCESS_NEW_PERM_MAP": "Novo mapa de permiss\u00e3o criado", 
    "END_SURVEY": "Finalizar Pesquisa Agora", 
    "CONFIRM_UNSAVED_CHANGES": "Existem altera\u00e7\u00f5es n\u00e3o salvas para um ou mais tipos de organiza\u00e7\u00f5es. Clique OK para salva-las, ou Cancelar para abandona-las.", 
    "OPAC_VISIBLE": "OPAC Vis\u00edvel", 
    "ERROR_DELETING": "Problema ao Excluir $(0)", 
    "ERROR_FETCHING_TYPES_AOUT": "Problema ao obter tipos de unidade organizacional", 
    "CONFIRM_DELETE": "Voc\u00ea tem certeza que quer excluir ${0}?", 
    "ERROR_ORPHANS": "N\u00e3o pode excluir ${0}, ainda existem ${1} itens subordinados.", 
    "LABEL_DEPTH": "Profundidade", 
    "LABEL_NEW_TYPE": "Novo Tipo", 
    "LABEL_VALUE": "Valor", 
    "SUCCESS_CREATING_CHILD_AOU": "Nova Unidade Organizacional filha criada para $(0)", 
    "EVENT_DEF_LABEL": "${0}: ${1}", 
    "ERROR_FETCHING_PHYSICAL": "Problema ao Trazer Endere\u00e7o F\u00edsico para $(0)", 
    "CONFIRM_EXIT_PPL": "Existem altera\u00e7\u00f5es n\u00e3o salvas para permiss\u00f5es. Clique OK para salva-las, ou Cancelar para abandona-las.", 
    "ERROR_FETCHING_PERMS": "Problema ao obter permiss\u00f5es", 
    "LABEL_NEW_GROUP": "Novo Grupo", 
    "SUCCESS_SAVING_HOO": "Horas em Opera\u00e7\u00e3o, atualizado para ${0}", 
    "ERROR_SAVING_STATUS": "Problema ao salvar $(0)", 
    "ERROR_SAVING_PHYSICAL": "Problema ao salvar dados de Endere\u00e7o F\u00edsico para $(0)", 
    "CONFIRM_EXIT_AOU": "Existem altera\u00e7\u00f5es n\u00e3o salvas para um ou mais unidades organizacionais. Clique OK para salva-las, ou Cancelar para abandona-las.", 
    "ERROR_DELETING_PERM_MAPPING": "Problema ao excluir mapa de permiss\u00e3o $(0)", 
    "ERROR_SAVING_DATA_CAM": "Problema ao salvar dados para $(0) $(1)", 
    "SUCCESS_SAVING_MAILING": "Salvo altera\u00e7\u00f5es para o Endere\u00e7o de Correspond\u00eancia para $(0)", 
    "ERROR_FETCHING_MAILING": "Problema ao obter Endere\u00e7os de Correspond\u00eancia para $(0)", 
    "ACQ_DISTRIB_FORMULA_NAME_CLONE": "${0} (Clone)", 
    "ERROR_CREATING_CHILD_GROUP": "Problema ao criar Grupo filho", 
    "ERROR_DELETING_LAST_AOU": "N\u00e3o pode-se excluir ${0}, pois \u00e9 necess\u00e1rio de uma unidade organizacional no m\u00ednimo.", 
    "ERROR_SAVING_HOLDS": "Problema ao salvar dados de Endere\u00e7o de Reservas para $(0)", 
    "NAME": "Nome", 
    "SUCCESS_CREATING_CHILD_AOUT": "Novo Tipo de Organiza\u00e7\u00e3o filha criado para $(0)", 
    "LABEL_GRANTABLE": "Tabela de Permiss\u00f5es", 
    "ERROR_SAVING_ILL": "Problema ao salvar dados de Endere\u00e7o de ILL para $(0)", 
    "SURVEY_FOOT_LABEL": "Perguntas & Respostas", 
    "ERROR_FETCHING_GROUPS": "Problema ao Trazer grupos", 
    "SUCCESS_CREATING_PERMISSION": "Nova $(0) permiss\u00e3o criada", 
    "SURVEY_ID": "ID da Pesquisa # {0}", 
    "ERROR_CREATING_PERM_MAP": "Problema ao criar  novo Mapa de Permiss\u00e3o", 
    "SURVEY_DELETE_ANSWER": "Excluir Resposta", 
    "SURVEY_QUESTION": "Pergunta:", 
    "CONFIRM_EXIT_CAM": "Existem altera\u00e7\u00f5es n\u00e3o salvas para um ou mais $(0) c\u00f3digos. Clique OK para salvar essas altera\u00e7\u00f5es, ou Cancelar para abandonalas.", 
    "ERROR_DELETING_LAST_AOUT": "N\u00e3o pode-se excluir ${0}, pois \u00e9 necess\u00e1rio de um tipo de organiza\u00e7\u00e3o no m\u00ednimo.", 
    "ERROR_FETCHING_ILL": "Problema ao obter Endere\u00e7os de ILL para $(0)", 
    "ERROR_CREATING_CHILD_AOUT": "Problema ao criar tipo do organiza\u00e7\u00e3o filha", 
    "ERROR_CALLING_METHOD_PGT": "Problema ao chamar m\u00e9todo para criar Grupo filho", 
    "CONFIRM_EXIT_PGT": "Existem altera\u00e7\u00f5es n\u00e3o salvas para mapas de permiss\u00f5es. Clique OK para salva-las, ou Cancelar para abandona-las.", 
    "SURVEY_ANSWER": "Resposta:", 
    "ERROR_FETCHING_PERM_MAPS": "Problema ao obter mapas de permiss\u00e3o", 
    "SURVEY_SAVE_ADD": "Salvar Pergunta & Adicionar Resposta", 
    "SUCCESS_SAVE": "Salvo altera\u00e7\u00f5es para $(0)", 
    "ERROR_CALLING_METHOD_PERM_MAP": "Problema ao chamar m\u00e9todo para criar novo mapa de permiss\u00e3o", 
    "LABEL_CODE": "C\u00f3digo", 
    "SURVEY_DELETE_QUESTION": "Excluir Perguntas & Respostas", 
    "SUCCESS_SAVE_PERM": "Salvo altera\u00e7\u00f5es de permiss\u00e3o para $(0)", 
    "SURVEY_ADD_ANSWER": "Adicionar Resposta", 
    "ERROR_FETCHING_STATUSES": "Problema ao obter situa\u00e7\u00f5es", 
    "ID": "ID", 
    "ERROR_CALLING_METHOD_CAM": "Problema ao chamar m\u00e9todo para criar novo(a) $(0)", 
    "ERROR_SAVING_MAILING": "Problema ao salvar dados de Endere\u00e7o de Corespond\u00eancia para $(0)", 
    "ERROR_CALLING_METHOD_AOUT": "Problema ao chamar m\u00e9todo para criar tipo de organiza\u00e7\u00e3o filha.", 
    "ERROR_CREATING_STATUS": "Problema ao criar nova Situa\u00e7\u00e3o", 
    "SUCCESS_NEW_CHILD_GROUP": "Novo Grupo Filho criado para ${0}"
}