{
    "SUCCESS_SAVING_PHYSICAL": "Salvar cambios de la dirrecion del correo ${0}", 
    "CONFIRM_EXIT_CCS": "Existen cambios sin guardar en uno o mas tipos de organizaci\u00f3n. Click OK para guardar estos cambios, o Cancelar para abandonarlos.", 
    "SURVEY_SAVE_CHANGES": "Guardar Cambios", 
    "ERROR_CREATING_CHILD_AOU": "Problema creando unidad organizacional hija.", 
    "ERROR_CALLING_METHOD_PPL": "Problema llamando al crear un nuevo permiso", 
    "TRANSLATION": "Translation", 
    "ERROR_FETCHING_ORGS": "Problema al obtener informaci\u00f3n de unidad organizacional", 
    "SUCCESS_CREATING_STATUS": "Nuevo ${0} porcentaje de creado", 
    "SUCCESS_SAVING_HOLDS": "Salvados los cambios de la dirrecion \"ILL\"", 
    "SUCCESS_SAVING_ILL": "Salvados los cambios de la dirrecion \"ILL\"", 
    "STATUS_EDITING": "Now editing ${0}", 
    "SUCCESS_SAVING_DATA": "Datos guardados de ${0}", 
    "SUCCESS_DELETED_PERM_MAP": "Permission mapping deleted", 
    "ERROR_SAVING_PERM_DATA": "Problema al salvar datos del permiso ${0}", 
    "ERROR_FETCHING_HOLDS": "Problema al obtener Direcci\u00f3n ILL para ${0}", 
    "HOLDABLE": "Sostenible", 
    "STATUS_DELETED": "${0} eliminado", 
    "ERROR_CALLING_METHOD_CCS": "Problema llamando al crear un nuevo permiso", 
    "SUCCESS_CREATING_CODE": "New ${0} ${1} created", 
    "ACQ_DISTRIB_FORMULA_NAME_PROMPT": "Enter new formula name", 
    "ERROR_SAVING_DATA": "Problem saving data for ${0}", 
    "LABEL_NEW_BRANCH": "New Branch", 
    "ERROR_FETCHING_HOURS": "Problema al obtener horas de operaci\u00f3n para ${0}", 
    "LABEL_TRANSLATION": "Translation", 
    "ERROR_CREATING_PERMISSION": "Problema al crear un nuevo permiso", 
    "LABEL_DESCRIPTION": "Descripci\u00f3n", 
    "ERROR_SAVING_HOO": "Problem saving Hours of Operation data for ${0}", 
    "SUCCESS_NEW_PERM_MAP": "Nuevo permiso para crear mapa", 
    "END_SURVEY": "Finalizar Encuesta Ahora", 
    "CONFIRM_UNSAVED_CHANGES": "Existen cambios sin guardar en uno o mas tipos de organizaci\u00f3n. Click OK para guardar estos cambios, o Cancelar para abandonarlos.", 
    "OPAC_VISIBLE": "OPAC Visible", 
    "ERROR_DELETING": "Problema salvando ${0}", 
    "ERROR_FETCHING_TYPES_AOUT": "Problema al obtener informaci\u00f3n de unidad organizacional", 
    "CONFIRM_DELETE": "Estas seguro que quieres eliminar ${0}?", 
    "ERROR_ORPHANS": "Cannot delete ${0}, ${1} subordinates still exist.", 
    "LABEL_DEPTH": "Depth", 
    "LABEL_NEW_TYPE": "Nuevo Tipo", 
    "LABEL_VALUE": "Value", 
    "SUCCESS_CREATING_CHILD_AOU": "Nuevo Tipo de Organizaci\u00f3n hijo creado para ${0}", 
    "EVENT_DEF_LABEL": "${0}: ${1}", 
    "ERROR_FETCHING_PHYSICAL": "Problema al extraer la Direcci\u00f3n de Correo para ${0}", 
    "CONFIRM_EXIT_PPL": "There are unsaved modified permissions. Click OK to save these changes, or Cancel to abandon them.", 
    "ERROR_FETCHING_PERMS": "Problema al obtener mapa de permisos", 
    "LABEL_NEW_GROUP": "New Group", 
    "SUCCESS_SAVING_HOO": "Hours of Operation updated for ${0}", 
    "ERROR_SAVING_STATUS": "Problema salvando ${0}", 
    "ERROR_SAVING_PHYSICAL": "Problem saving Physical Address data for ${0}", 
    "CONFIRM_EXIT_AOU": "Existen cambios sin guardar en uno o mas tipos de organizaci\u00f3n. Click OK para guardar estos cambios, o Cancelar para abandonarlos.", 
    "ERROR_DELETING_PERM_MAPPING": "Problem deleting permission mapping ${0}", 
    "ERROR_SAVING_DATA_CAM": "Problem saving data for ${0} ${1}", 
    "SUCCESS_SAVING_MAILING": "Salvar cambios de la dirrecion del correo ${0}", 
    "ERROR_FETCHING_MAILING": "Problema al extraer la Direcci\u00f3n de Correo para ${0}", 
    "ACQ_DISTRIB_FORMULA_NAME_CLONE": "${0} (Clone)", 
    "ERROR_CREATING_CHILD_GROUP": "Problem creating child Group", 
    "ERROR_DELETING_LAST_AOU": "Cannot delete ${0}, you need at least one organization unit.", 
    "ERROR_SAVING_HOLDS": "Problem saving Holds Address data for ${0}", 
    "NAME": "Name", 
    "SUCCESS_CREATING_CHILD_AOUT": "Nuevo Tipo de Organizaci\u00f3n hijo creado para ${0}", 
    "LABEL_GRANTABLE": "Puede hacerse", 
    "ERROR_SAVING_ILL": "Problema al obtener Direcci\u00f3n ILL para ${0}", 
    "SURVEY_FOOT_LABEL": "Questions & Answers", 
    "ERROR_FETCHING_GROUPS": "Problema al obtener mapa de permisos", 
    "SUCCESS_CREATING_PERMISSION": "New ${0} permission created", 
    "SURVEY_ID": "Estudio de ID # ${0}", 
    "ERROR_CREATING_PERM_MAP": "Problema al crear nuevo Mapa de Permisos", 
    "SURVEY_DELETE_ANSWER": "Eliminar pregunta", 
    "SURVEY_QUESTION": "Question:", 
    "CONFIRM_EXIT_CAM": "Existen cambios sin guardar en uno o mas tipos de organizaci\u00f3n. Click OK para guardar estos cambios, o Cancelar para abandonarlos.", 
    "ERROR_DELETING_LAST_AOUT": "Cannot delete ${0}. You need at least one organization type.", 
    "ERROR_FETCHING_ILL": "Problema al obtener Direcci\u00f3n ILL para ${0}", 
    "ERROR_CREATING_CHILD_AOUT": "Problema creando unidad organizacional hija.", 
    "ERROR_CALLING_METHOD_PGT": "Problema al llamar m\u00e9todo para crear Grupo hijo", 
    "CONFIRM_EXIT_PGT": "There are unsaved modified permission maps. Click OK to save these changes, or Cancel to abandon them.", 
    "SURVEY_ANSWER": "Answer:", 
    "ERROR_FETCHING_PERM_MAPS": "Problema al obtener mapa de permisos", 
    "SURVEY_SAVE_ADD": "Save Question & Add Answer", 
    "SUCCESS_SAVE": "Datos guardados de ${0}", 
    "ERROR_CALLING_METHOD_PERM_MAP": "Problema llamando al crear un nuevo permiso", 
    "LABEL_CODE": "Code", 
    "SURVEY_DELETE_QUESTION": "Delete Question & Answers", 
    "SUCCESS_SAVE_PERM": "Saved permission changes to ${0}", 
    "SURVEY_ADD_ANSWER": "Agregar Respuesta", 
    "ERROR_FETCHING_STATUSES": "Problem fetching statuses", 
    "ID": "ID", 
    "ERROR_CALLING_METHOD_CAM": "Problema al llamar al m\u00e9todo para crear nuevo ${0}", 
    "ERROR_SAVING_MAILING": "Problema al extraer la Direcci\u00f3n de Correo para ${0}", 
    "ERROR_CALLING_METHOD_AOUT": "Problema al llamar m\u00e9todo para crear Grupo hijo", 
    "ERROR_CREATING_STATUS": "Problem creating new Status", 
    "SUCCESS_NEW_CHILD_GROUP": "Nuevo Grupo hijo creado para ${0}"
}