{
    "PWD_RESET_SUBMIT_ERROR": "The system could not process your request for a password reset. Please try again, or contact circulation staff for assistance.", 
    "PWD_RESET_SUBMIT_SUCCESS": "Your request to begin the password reset process has been processed. If your account has a valid email address, you should soon receive an email containing further instructions for resetting your password.", 
    "USERNAME_PROMPT": "User name: ", 
    "HOLD_STATUS_PLURAL": "hold # ${0} of ${1} total holds and ${2} potential items", 
    "HOLDINGS_TABLE_CAPTION": "Holdings summary (${0})", 
    "INDEX_HOLDINGS": "Indexes", 
    "EDIT_MFHD_RECORD": "Eintrag bearbeiten", 
    "MISSING_VOLUMES": "Missing volumes", 
    "DELETED_MFHD_RECORD": "MFHD Eintrag ${0} l\u00f6schen", 
    "SUBMIT_BUTTON_LABEL": "Submit", 
    "CREATED_MFHD_RECORD": "MFHD Eintrag erstellt f\u00fcr ${0}", 
    "CURRENT_INDEXES": "Current indexes", 
    "BARCODE_PROMPT": "Barcode: ", 
    "PWD_RESET_RESPONSE_TITLE": "Password reset response", 
    "CURRENT_SUPPLEMENTS": "Current supplements", 
    "ONLINE_VOLUMES": "Online volumes", 
    "DELETE_MFHD": "Eintrag l\u00f6schen", 
    "CREATE_MFHD": "MFHD Eintrag hinzuf\u00fcgen", 
    "EDIT_PROPERTIES": "Einstellungen bearbeiten", 
    "CANCEL_BUTTON_LABEL": "Cancel", 
    "CURRENT_HOLDINGS": "Current volume", 
    "MORE_COPIES_FULL_RECORD": "... more copies listed in full record", 
    "SUPPLEMENT_HOLDINGS_ADD": "Additional Supplement Information", 
    "INCOMPLETE_VOLUMES": "Incomplete volumes", 
    "SAVE_MFHD_LABEL": "MFHD speichern", 
    "OK": "OK", 
    "INDEX_HOLDINGS_ADD": "Additional Index Information", 
    "PWD_RESET_FORGOT_PROMPT": "Forgot your password?", 
    "PWD_RESET_FORM_TITLE": "Request password reset", 
    "PWD_RESET_SUBMIT_PROMPT": "To begin the password reset process, enter either your barcode or user name in the form below and click 'Submit'", 
    "HOLD_STATUS_SINGULAR": "hold # ${0} of ${1} total holds and ${2} potential item", 
    "PWD_RESET_SUBMIT_STATUS": "Sending request...", 
    "DELETE_MFHD_CONFIRM": "Are you sure you want to delete this serial record?", 
    "PLACE_HOLD": "Place hold", 
    "BASIC_HOLDINGS": "Volumes", 
    "EDIT_MFHD_MENU": "Edit Holdings", 
    "BASIC_HOLDINGS_ADD": "Additional Volume Information", 
    "SUPPLEMENT_HOLDINGS": "Supplements", 
    "MORE": "More"
}