{
    "PWD_RESET_SUBMIT_ERROR": "El sistema no pudo procesar su solicitud para el restablecimiento de su contrase\u00f1a. Por favor intente de nuevo, o contacte personal de circulaci\u00f3n por asistencia.", 
    "PWD_RESET_SUBMIT_SUCCESS": "Su solicitud para iniciar el proceso de reinicializacion de contrase\u00f1a a sido procesado. Si su cuenta tiene una direcci\u00f3n de correo electr\u00f3nico v\u00e1lida, usted debe recibir un correo electr\u00f3nico que contiene m\u00e1s instrucciones para reinicializar su contrase\u00f1a.", 
    "USERNAME_PROMPT": "Nombre de usuario: ", 
    "HOLD_STATUS_PLURAL": "hold # ${0} of ${1} total holds and ${2} potential items", 
    "HOLDINGS_TABLE_CAPTION": "Resumen de las explotaciones (${0})", 
    "INDEX_HOLDINGS": "\u00cdndices", 
    "EDIT_MFHD_RECORD": "Editar registro", 
    "MISSING_VOLUMES": "Vol\u00famenes faltantes", 
    "DELETED_MFHD_RECORD": "Eliminar registro MFHD ${0}", 
    "SUBMIT_BUTTON_LABEL": "Presentar", 
    "CREATED_MFHD_RECORD": "Se cre\u00f3 un registro MFHD para ${0}", 
    "CURRENT_INDEXES": "\u00cdndices actuales", 
    "BARCODE_PROMPT": "C\u00f3digo de barras: ", 
    "PWD_RESET_RESPONSE_TITLE": "Respuesta para el restablecimiento de la contrase\u00f1a", 
    "CURRENT_SUPPLEMENTS": "Suplementos actuales", 
    "ONLINE_VOLUMES": "Vol\u00famenes en l\u00ednea", 
    "DELETE_MFHD": "Eliminar registro", 
    "CREATE_MFHD": "A\u00f1adir registro MFFHD", 
    "EDIT_PROPERTIES": "Editar propiedades", 
    "CANCEL_BUTTON_LABEL": "Cancelar", 
    "CURRENT_HOLDINGS": "Volumen actual", 
    "MORE_COPIES_FULL_RECORD": "... more copies listed in full record", 
    "SUPPLEMENT_HOLDINGS_ADD": "Informaci\u00f3n adicional de suplemento", 
    "INCOMPLETE_VOLUMES": "Vol\u00famenes Incompletos", 
    "SAVE_MFHD_LABEL": "Guardar MFHD", 
    "OK": "Aceptar", 
    "INDEX_HOLDINGS_ADD": "Informaci\u00f3n adicional del \u00edndice", 
    "PWD_RESET_FORGOT_PROMPT": "Se le olvido la contrase\u00f1a?", 
    "PWD_RESET_FORM_TITLE": "Solicite restablecer la contrase\u00f1a", 
    "PWD_RESET_SUBMIT_PROMPT": "Para empezar el proceso de restablecer la contrase\u00f1a, ingrese su c\u00f3digo de barras o su nombre de usuario en el formulario debajo y haga clic en 'presentar'", 
    "HOLD_STATUS_SINGULAR": "hold # ${0} of ${1} total holds and ${2} potential item", 
    "PWD_RESET_SUBMIT_STATUS": "Enviando solicitud...", 
    "DELETE_MFHD_CONFIRM": "\u00bfEsta seguro de que desea borrar el registro de serie?", 
    "PLACE_HOLD": "Place hold", 
    "BASIC_HOLDINGS": "Vol\u00famenes", 
    "EDIT_MFHD_MENU": "Editar Explotaciones", 
    "BASIC_HOLDINGS_ADD": "Informaci\u00f3n adicional del volumen", 
    "SUPPLEMENT_HOLDINGS": "Suplementos", 
    "MORE": "More"
}