{
    "SOURCE_SETUP_ALL_AVAIL_SOURCES": "All Available Sources", 
    "TEMPLATE_CONF_SELECT_CANCEL": "Select the value, or cancel:", 
    "OPERATORS_ILIKE": "Contains Matching substring (ignore case)", 
    "FILTERS_LABEL_NULL_BLANK": "Is NULL or Blank", 
    "OPERATORS_LIKE": "Contains Matching substring", 
    "WIDGET_MONTHS": "Ay(lar)", 
    "LINK_NULLABLE_RIGHT": "Parent", 
    "TFORMS_LABEL_AVERAGE": "Ortalama", 
    "TEMPLATE_CONF_CONFIRM_STATE": "Click OK for TRUE and Cancel for FALSE.", 
    "OPERATORS_EQUALS": "Equals", 
    "FILTERS_LABEL_BETWEEN": "Between", 
    "OPERATORS_IN_LIST": "In list", 
    "TEMPLATE_CONF_NOT_IN": "Field does not match one of list (comma separated):", 
    "OPERATORS_NOT_IN_LIST": "Listede yok", 
    "FILTERS_LABEL_NOT_IN": "Listede yok", 
    "SOURCE_BROWSE_NON_AGGREGATE": "Non-Aggregate", 
    "FILTERS_LABEL_GT_TIME": "After (Date/Time)", 
    "OPERATORS_IS_NULL": "Is NULL", 
    "TEMPLATE_CONF_CONFIRM_SAVE": "Name : ${0}\nDescription: ${1}\nSave Template?", 
    "OPERATORS_IS_NOT_NULL": "Is not NULL", 
    "TEMPLATE_CONF_CONFIRM_RESET": "You have already added the [${0}] field\nfrom the [${1}] source. Click OK if you\nwould like to reset this field.", 
    "OPERATORS_GT_EQUAL": "Greater than or equal to", 
    "TRANSFORMS_MONTH_TRUNC": "Y\u0131l +Ay", 
    "FILTERS_LABEL_NULL": "Is NULL", 
    "REPORT_EDITOR_PROVIDE_FOLDER_ALERT": "Please provide a report folder", 
    "OPERATORS_GT_TIME": "After (Date/Time)", 
    "TRANSFORMS_YEAR_TRUNC": "Y\u0131l", 
    "TRANSFORMS_UPPER": "B\u00fcy\u00fck harf", 
    "FOLDERS_REPORTS": "Raporlar", 
    "LINK_NULLABLE_LEFT": "Child", 
    "TRANSFORMS_COUNT_DISTINCT": "Count Distinct", 
    "FOLDER_WINDOW_COLNAME_SELECT": "Se\u00e7", 
    "TRANSFORMS_FIRST": "\u0130lk De\u011fer", 
    "TFORMS_LABEL_LOWER": "K\u00fc\u00e7\u00fck harf", 
    "TFORMS_LABEL_COUNT": "Saya\u00e7", 
    "TRANSFORMS_HOD": "G\u00fcn\u00fcn saati", 
    "WIDGET_RELATIVE_DATE": "Relative Date", 
    "FILTERS_LABEL_LESS_THAN": "K\u00fc\u00e7\u00fckt\u00fcr", 
    "TEMPLATE_CONF_SUCCESS_SAVE": "Template ${0} was successfully saved.", 
    "TFORMS_LABEL_MOY": "Y\u0131l\u0131n Ay\u0131", 
    "FILTERS_LABEL_EQ_ANY": "Equals Any", 
    "TRANSFORMS_MAX": "Max", 
    "TRANSFORMS_MIN": "Min", 
    "TRANSFORMS_SUM": "Toplam", 
    "TRANSFORMS_FIRST_WORD": "First contiguous non-space string", 
    "TRANSFORMS_MONTHS_AGO": "Ay \u00f6nce", 
    "SOURCE_BROWSE_AGGREGATE": "Aggregate", 
    "TFORMS_LABEL_DATE": "Tarih", 
    "WIDGET_YEARS": "Y\u0131l(lar)", 
    "FILTERS_LABEL_LT_TIME": "Before (Date/Time)", 
    "TRANSFORMS_COUNT": "Saya\u00e7", 
    "WIDGET_REAL_DATE": "Real Date", 
    "OPERATORS_LT_TIME": "Before (Date/Time)", 
    "TFORMS_LABEL_MAX": "Max", 
    "TEMPLATE_CONF_FALSE": "False", 
    "TEMPLATE_CONF_BARE": "Bare", 
    "TRANSFORMS_LAST": "Son De\u011fer", 
    "TFORMS_LABEL_MIN": "Min", 
    "REPORT_EDITOR_REPORT_FOLDERS": "Rapor Klas\u00f6rleri", 
    "TEMPLATE_CONF_EQUALS": "Equals", 
    "REPORT_EDITOR_OUTPUT_FOLDERS": "\u00c7\u0131kt\u0131 Klas\u00f6rleri", 
    "FILTERS_LABEL_NOT_BETWEEN": "Not between", 
    "TRANSFORMS_QOY": "Y\u0131l\u0131n \u00c7eyre\u011fi", 
    "REPORT_EDITOR_PROVIDE_OUTPUT_ALERT": "Please provide an output folder", 
    "FILTERS_LABEL_GREATER_THAN": "B\u00fcy\u00fckt\u00fcr", 
    "FILTERS_LABEL_NE_ANY": "Does Not Equal Any", 
    "FOLDERS_OUTPUT": "\u00c7\u0131kt\u0131", 
    "OPERATORS_NE_ANY": "Does Not Equal Any", 
    "TRANSFORMS_AVERAGE": "Ortalama", 
    "FOLDERS_TEMPLATES": "\u015eablonlar", 
    "TFORMS_LABEL_DAY_NAME": "G\u00fcn Ad\u0131", 
    "WIDGET_DAYS": "G\u00fcn(ler)", 
    "TRANSFORMS_ROUND": "Round", 
    "FOLDERS_TEMPLATE": "\u015eablon", 
    "TRANSFORMS_HOUR_TRUNC": "Saat", 
    "TFORMS_LABEL_HOUR_TRUNC": "Saat", 
    "TRANSFORMS_MOY": "Y\u0131l\u0131n Ay\u0131", 
    "LINK_NULLABLE_NONE": "None", 
    "RPT_BUILDER_CONFIRM_SAVE": "Name : ${0}\nDescription: ${1}\nSave Template?", 
    "TFORMS_LABEL_DOY": "Y\u0131l\u0131n G\u00fcn\u00fc", 
    "TRANSFORMS_DATE": "Tarih", 
    "FOLDERS_REPORT": "Rapor", 
    "TFORMS_LABEL_DOW": "Haftan\u0131n G\u00fcn\u00fc", 
    "FILTERS_LABEL_LT_EQUAL": "Less than or equal to", 
    "TFORMS_LABEL_INT": "Drop trailing decimals", 
    "OPERATORS_GTE_TIME": "On or After (Date/Time)", 
    "TFORMS_LABEL_DOM": "Ay\u0131n G\u00fcn\u00fc", 
    "FOLDER_WINDOW_COLNAME_NONE": "None", 
    "REPORT_EDITOR_ENTER_NAME_ALERT": "Please enter a report name", 
    "OPERATORS_LT_EQUAL": "Less than or equal to", 
    "TFORMS_LABEL_MONTHS_AGO": "Ay \u00f6nce", 
    "TFORMS_LABEL_FIRST_WORD": "First contiguous non-space string", 
    "FOLDER_WINDOW_REPORT_OUTPUT": "Report Output: ${0}", 
    "FILTERS_LABEL_GTE_TIME": "On or After (Date/Time)", 
    "TFORMS_LABEL_FIRST": "\u0130lk De\u011fer", 
    "TRANSFORMS_AGE": "Ya\u015f", 
    "FILTERS_LABEL_LIKE": "Contains Matching substring", 
    "TEMPLATE_CONF_TRUE": "True", 
    "SOURCE_SETUP_CONFIRM_EXIT": "You have started building a template!\n Selecting a new starting source will destroy the current template and start over.  Is this OK?", 
    "TRANSFORMS_QUARTERS_AGO": "Quarters ago", 
    "TFORMS_LABEL_MONTH_TRUNC": "Y\u0131l +Ay", 
    "TEMPLATE_CONF_IN": "Field matches one of list (comma separated):", 
    "FILTERS_LABEL_ILIKE": "Contains Matching substring (ignore case)", 
    "FILTERS_LABEL_NOT_NULL": "Is not NULL", 
    "TEMPLATE_CONF_NO_MATCH": "Field does not match one of list (comma separated):", 
    "TFORMS_LABEL_UPPER": "B\u00fcy\u00fck harf", 
    "TRANSFORMS_SUBSTRING": "Substring", 
    "FILTERS_LABEL_GT_EQUAL": "Greater than or equal to", 
    "TEMPLATE_CONF_RAW_DATA": "Raw Data", 
    "TFORMS_LABEL_HOD": "G\u00fcn\u00fcn saati", 
    "FILTERS_LABEL_NOT_NULL_BLANK": "Is not NULL or Blank", 
    "TFORMS_LABEL_SUM": "Toplam", 
    "LINK_NULLABLE_DEFAULT": "Varsay\u0131lan", 
    "FILTERS_LABEL_IN": "In list", 
    "TFORMS_LABEL_AGE": "Ya\u015f", 
    "FOLDER_WINDOW_CHANGE_FOLDERS": "Change Folders", 
    "TRANSFORMS_LOWER": "K\u00fc\u00e7\u00fck harf", 
    "TRANSFORMS_MONTH_NAME": "Ay Ad\u0131", 
    "TRANSFORMS_DOW": "Haftan\u0131n G\u00fcn\u00fc", 
    "TEMPLATE_CONF_PROMPT_CHANGE": "Change the column header to: ${0}", 
    "OPERATORS_NOT_BETWEEN": "Not between", 
    "TRANSFORMS_DOY": "Y\u0131l\u0131n G\u00fcn\u00fc", 
    "REPORT_EDITOR_INVALID_DATE_ALERT": "invalid start date -  YYYY-MM-DD", 
    "TRANSFORMS_BARE": "Raw Data", 
    "TRANSFORMS_DOM": "Ay\u0131n G\u00fcn\u00fc", 
    "TFORMS_LABEL_MONTH_NAME": "Ay Ad\u0131", 
    "OPERATORS_EQ_ANY": "Equals Any", 
    "TFORMS_LABEL_ROUND": "Round", 
    "OPERATORS_GREATER_THAN": "B\u00fcy\u00fckt\u00fcr", 
    "SOURCE_SETUP_CORE_SOURCES": "Core Sources", 
    "TFORMS_LABEL_LAST": "Son De\u011fer", 
    "FILTERS_LABEL_EQUALS": "Equals", 
    "FOLDER_WINDOW_COLNAME_ALL": "T\u00fcm\u00fc", 
    "TFORMS_LABEL_RAW_DATA": "Raw Data", 
    "TFORMS_LABEL_COUNT_DISTINCT": "Count Distinct", 
    "TFORMS_LABEL_FIRST5": "First 5 characters (for US ZIP code)", 
    "TEMPLATE_CONF_NOT_BETWEEN": "Field value is not between (comma separated):", 
    "TRANSFORMS_INT": "Drop trailing decimals", 
    "FILTERS_LABEL_LSE_TIME": "On or Before (Date/Time)", 
    "TRANSFORMS_DAY_NAME": "G\u00fcn Ad\u0131", 
    "FOLDER_WINDOW_SELECT_ITEM": "Please select an item from the list", 
    "TRANSFORMS_FIRST5": "First 5 characters (for US ZIP code)", 
    "OPERATORS_LTE_TIME": "On or Before (Date/Time)", 
    "TEMPLATE_CONF_DEFAULT": "Value ${0}:", 
    "TFORMS_LABEL_YEAR_TRUNC": "Y\u0131l", 
    "TRANSFORMS_WOY": "Y\u0131l\u0131n Haftas\u0131", 
    "TFORMS_LABEL_WOY": "Y\u0131l\u0131n Haftas\u0131", 
    "TFORMS_LABEL_QUARTERS_AGO": "Quarters ago", 
    "TEMPLATE_CONF_BOOLEAN_VALUE": "Boolean Value", 
    "OPERATORS_NOT_NULL_BLANK": "Is not NULL or Blank", 
    "OPERATORS_NULL_BLANK": "Is NULL or Blank", 
    "TEMPLATE_CONF_BETWEEN": "Field value is between (comma separated):", 
    "TFORMS_LABEL_QOY": "Y\u0131l\u0131n \u00c7eyre\u011fi", 
    "WIDGET_QUARTERS": "Quarter(s)", 
    "OPERATORS_LESS_THAN": "K\u00fc\u00e7\u00fckt\u00fcr", 
    "OPERATORS_BETWEEN": "Between"
}